Repository mauv2sky/Cooker_Site, pull requests merged in 2022-04, with the labels that each got.

#6 Boss mvp back
  back/db/models/index.js
  back/db/models/schemas/bossUser.js
  back/package-lock.json
Labels: backend, 누리

#13 [Add] 에러 미들웨어 구현
  back/src/middlewares/errorMiddleware.js
Labels: backend, 누리

#15 [Add] Boss mvp back 회원가입 구현
  back/db/models/index.js
  back/db/models/model/BossUser.js
  back/db/models/schemas/bossUser.js
  back/package-lock.json
  back/package.json
  back/src/app.js
  back/src/routers/bossUserRouter.js
  back/src/services/bossUserService.js
Labels: bug, backend, 누리

#14 [Add] 유저 MVP CRUD
  back/db/models/index.js
  back/db/models/model/User.js
  back/db/models/schemas/user.js
  back/package-lock.json
  back/package.json
  back/src/app.js
  back/src/middlewares/login_required.js
  back/src/routers/userRouter.js
  back/src/services/userService.js
Labels: 아현, backend

#16 [Modify] Boss mvp back 컨벤션 통일
  back/db/models/model/BossUser.js
  back/db/models/schemas/bossUser.js
  back/src/routers/bossUserRouter.js
  back/src/services/bossUserService.js
Labels: bug, backend, 누리

#18 유저 MVP 비밀번호 찾기 구현
  back/db/models/model/User.js
  back/package-lock.json
  back/package.json
  back/src/routers/userRouter.js
  back/src/services/userService.js
Labels: 아현, backend

#19 Boss mvp back Merge
  back/src/routers/bossUserRouter.js
  back/src/routers/userRouter.js
  back/src/services/bossUserService.js
Labels: backend, 누리
